# Generated by Django 2.1.3 on 2018-11-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
        ('hospital', '0001_initial'),
        ('medico', '0001_initial'),
        ('core_consultas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultas',
            name='hospital',
            field=models.ManyToManyField(to='hospital.Hospital'),
        ),
        migrations.AddField(
            model_name='consultas',
            name='medico',
            field=models.ManyToManyField(to='medico.Medico'),
        ),
        migrations.AddField(
            model_name='consultas',
            name='paciente',
            field=models.ManyToManyField(to='paciente.Paciente'),
        ),
    ]
