# Generated by Django 2.1.3 on 2018-11-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0001_initial'),
        ('core_consultas', '0004_consultas_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultas',
            name='avaliacao',
            field=models.ManyToManyField(to='avaliacao.Avaliacao'),
        ),
    ]
