# Generated by Django 2.1.3 on 2018-11-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('CPF', models.CharField(max_length=150)),
                ('endereco', models.CharField(max_length=150)),
                ('CEP', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=150)),
            ],
        ),
    ]
